services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app:create_app
      - DATABASE_URL=postgresql://user:password@db/app
      - SECRET_KEY=secretkey
      - PYTHONPATH=/app/src
    depends_on:
      - db

volumes:
  db_data:
